#!/bin/bash
# File              : sketch
# Author            : Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date              : Wed 31 Jul 00:49:59 2019
# Last Modified Date: Wed 31 Jul 00:49:59 2019
# Last Modified By  : Matthieu Petiteau <mpetiteau.pro@gmail.com>
#         __       __      __
#    ___ / /_____ / /_____/ /
#   (_-</  '_/ -_) __/ __/ _ \
#  /___/_/\_\\__/\__/\__/_//_/


# Temp folder for sketch files.
TEMP_SKETCH=$HOME/.sketch.swp
if [ ! -d $TEMP_SKETCH ]
then
  mkdir $TEMP_SKETCH
fi

# Load conf from possible locations.
conf_dir=(../.sketchconfig $HOME/.sketchconfig .sketchconfig)
for d in "${conf_dir[@]}"
do
  if [ -f $d ]
  then
    . $d
  fi
done

editor=$editor
if [[ -z $editor ]]
then
  # Default editor if no .sketchconfig detected.
  editor=vim
fi

param=$1

# New sketch.
if [[ -z $param ]]
then
  file=$(($(ls $TEMP_SKETCH | wc -l))).sketch
  $editor $TEMP_SKETCH/$file
# Re-open previous sketch files.
elif [[ $param == -l* ]] && [[ "${param:2}" =~ ^[0-9]+(\.[0-9]+)?$ ]]
then
  nb="${param:2}"
  av=$(ls $TEMP_SKETCH | wc -l)
  if [ $av -gt $nb ] || [ $av -eq $nb ]
  then
    file=$(($(ls $TEMP_SKETCH | wc -l) - $nb)).sketch
    $editor $TEMP_SKETCH/$file
  else
    echo "No previous*$nb sketch found"
  fi
# Clean sketchs.
elif [[ $param == "--purge" || $param == "-pu" ]]
then
  if [ -n "$(ls -A $TEMP_SKETCH 2>/dev/null)" ]
  then
    rm $TEMP_SKETCH/*
    echo "Sketch files have been purged."
  else
    echo "No files to purge."
  fi
elif [[ $param == "--help" || $param == "-h" ]]
then
  echo "       __       __      __ "
  echo "  ___ / /_____ / /_____/ / "
  echo " (_-</  '_/ -_) __/ __/ _ \'"
  echo "/___/_/\_\\__/\__/\__/_//_/"
  echo "                           "
  echo "Sketch is a small productivity tool to rapidly generate"
  echo "and access draft files from the terminal."
  echo "Created by Matthieu Petiteau <mpetiteau.pro@gmail.com>"
  echo " "
  echo "A nice thing is to alias in your .bashrc sketch to"
  echo "access it more easily. Personaly I'm using 'alias s=~/./sketch'"
  echo " "
  echo " "
  echo "PARAMETERS"
  echo "------------------------------------------------------------"
  echo " "
  echo "--help or -h"
  echo "Help and informations."
  echo " "
  echo "-l<number>"
  echo "Open archived sketch files saved. Example: -l1 will open the"
  echo "last sketch file saved. -l2 will open the previous one, etc."
  echo " "
  echo "--purge or -pu"
  echo "Purge all the files created in the temp dir under ~/.sketch.swp"
  echo " "
else
  echo "Command does not exist."
fi
